name: PR Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/**"
      - ".github/workflows/**"
      - ".github/actions/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "turbo.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Main validation job that runs quality checks and builds
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Build and test
        uses: ./.github/actions/build-and-test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/bpmn-js-markdown-documentation-panel/dist/
          retention-days: 1

  # Test examples to ensure they work with the current build
  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: packages/bpmn-js-markdown-documentation-panel/

      - name: Test examples
        run: |
          echo "🧪 Testing examples..."

          # Test viewer example
          cd examples/bpmn-viewer-example
          pnpm install
          pnpm run type-check
          pnpm run build
          echo "✅ Viewer example builds successfully"

          # Verify example can import the package
          echo "🔍 Verifying package integration..."
          if [ -f "../../packages/bpmn-js-markdown-documentation-panel/dist/bpmn-js-entry.js" ]; then
            echo "✅ Package build available for examples"
          else
            echo "❌ Package build missing"
            exit 1
          fi
