name: PR Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/**"
      - ".github/workflows/**"
      - ".github/actions/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "turbo.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Main validation job that runs quality checks and builds
  validate:
    name: Validate Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Build and test
        uses: ./.github/actions/build-and-test
